### PR TITLE
Navbar

### PR DESCRIPTION
**Pull request by coreycartercodes**
## Pull request type
Please check the type of change your PR introduces:
- [ ] Bugfix
- [x ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other (please describe):

## Problem/feature
Added navbar to application.html.erb and associated helper methods in application controller

## Solution
By creating the new resources.

## Checklist
- [ ] Code compiles correctly
- [ ] Tests for the changes have been added (for bug fixes/features)
- [ ] All tests passing
- [ ] No rubocop offenses
- [ ] Extended the README / documentation, if necessary

### CODE REVIEW

**Comment by coreycartercodes** [comment]
Hold off on merging, adding tests.

11/1 - 12:47pm

**Comment by coreycartercodes** [comment]
Will probably want to wait to Merge until Oauth and current_user are finished.

**Comment by TravisGM92** [comment]
> Will probably want to wait to Merge until Oauth and current_user are finished.
> 
> 11/1 - 3:55pm

It's failing all tests, is that expected?

**Comment by Callbritton** [comment]
Closing this PR to review Student Dashboard PR that includes the Navbar content

**Pull request closed without merging**
